---
title: "Regression V2"
output:
  html_document:
    fig_height: 8
    fig_width: 15
    toc_depth: 30
  pdf_document: 
    fig_width: 12
    toc_depth: 8
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE}

library("openxlsx")
library("ggplot2")
library("dplyr")
library("car")
library("Hmisc")
library("moments")
```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 1000)
regress_data <- read.xlsx(xlsxFile = './Data-after-cleanning-v2.xlsx',sheet=1,colNames=TRUE)
regress_data$X1 <- NULL
regress_data$X10 <- NULL
regress_data <- regress_data[-nrow(regress_data),]


sapply(regress_data, mean, na.rm=TRUE) #Mean
sapply(regress_data ,sd, na.rm=TRUE) # Standard deviation
sapply(regress_data ,var, na.rm=TRUE) # variance
sapply(regress_data ,skewness, na.rm=TRUE) # skewness


rcorr(as.matrix(regress_data)) # For correlation


pairs(~CAR0+DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism + Premium, data=regress_data, main="Scatterplots")

# 1). 
model1 <- lm(CAR0 ~ DealValue + RelativeSize + Division + GeographicalDistance, data=regress_data)
summary(model1)
vif(model1)

# 2). 

model2 <- lm(CAR0 ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium, data=regress_data)
summary(model2)
vif(model2)

# 3).

model3 <- lm(CAR0 ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism, data=regress_data)
summary(model3)
vif(model3)

# 4). 

model4 <- lm(CAR0 ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism +Premium*UncertaintyAvoidance + Premium*Individualism, data=regress_data)
summary(model4)
vif(model4)
```

```{r}
options(width = 1000)
regress_data <- read.xlsx(xlsxFile = './104.xlsx',sheet=1,colNames=TRUE)
regress_data$X1 <- NULL
regress_data$X10 <- NULL
regress_data <- regress_data[-nrow(regress_data),]


sapply(regress_data, mean, na.rm=TRUE) #Mean
sapply(regress_data ,sd, na.rm=TRUE) # Standard deviation
sapply(regress_data ,var, na.rm=TRUE) # variance
sapply(regress_data ,skewness, na.rm=TRUE) # skewness

rcorr(as.matrix(regress_data)) # For correlation


pairs(~CAR+DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism +Premium,data=regress_data, main="Scatterplots")

# 1). 
model1 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance, data=regress_data)
summary(model1)
vif(model1)

# 2). 

model2 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium, data=regress_data)
summary(model2)
vif(model2)

# 3).

model3 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism, data=regress_data)
summary(model3)
vif(model3)

# 4). 

model4 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism +Premium*UncertaintyAvoidance + Premium*Individualism, data=regress_data)
summary(model4)
vif(model4)

```


```{r}
options(width = 1000)
regress_data <- read.xlsx(xlsxFile = './105.xlsx',sheet=1,colNames=TRUE)
regress_data$X1 <- NULL
regress_data$X10 <- NULL
regress_data <- regress_data[-nrow(regress_data),]


sapply(regress_data, mean, na.rm=TRUE) #Mean
sapply(regress_data ,sd, na.rm=TRUE) # Standard deviation
sapply(regress_data ,var, na.rm=TRUE) # variance
sapply(regress_data ,skewness, na.rm=TRUE) # skewness

rcorr(as.matrix(regress_data)) # For correlation


pairs(~CAR+DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism +Premium,data=regress_data, main="Scatterplots")

# 1). 
model1 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance, data=regress_data)
summary(model1)
vif(model1)

# 2). 

model2 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium, data=regress_data)
summary(model2)
vif(model2)

# 3).

model3 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism, data=regress_data)
summary(model3)
vif(model3)

# 4). 

model4 <- lm(CAR ~ DealValue + RelativeSize + Division + GeographicalDistance + Premium + UncertaintyAvoidance + Individualism +Premium*UncertaintyAvoidance + Premium*Individualism, data=regress_data)
summary(model4)
vif(model4)
```